name: Build and Push to GHCR
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/Traybuns/platform-engineering-build-template:latest .
          docker push ghcr.io/Traybuns/platform-engineering-build-template:latest